[package]
name = "buggy"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.29"
config = "0.14.1"
crossterm = "0.28.1"
image = "0.25.5"
imageproc = "0.25.0"
indicatif = "0.17.9"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
