output_directory = "layouts"

[font]
path_regular = "fonts/Roboto-Regular.ttf"
path_bold = "fonts/Roboto-Bold.ttf"
size_title = 28.0
size_subtitle = 20.0

[layout]
width = 1000
height = 707
margin = 50
title_margin = 40
text_title = "Piantina di territorio"
text_subtitle_left = "Congregazione **Roma** Pratolungo"
text_subtitle_right = "**ZONA** <zone_name> **N.** <territory_number>"

[map]
maps_directory = "maps"

[map.crop]
top = 100
left = 50
bottom = 77
right = 82
